/*Selecionando clientes e seus veículos*/
SELECT C.NOME,
	V.TIPO,
    V.MARCA,
    V.MODELO,
    V.MARCA
FROM CLIENTE C 
LEFT JOIN VEICULO V
ON C.IDCLIENTE = V.IDCLIENTE;

/*Quantidades de ordens de serviço por cliente.*/
SELECT C.NOME,
	COUNT(O.IDORDEMSERVICO) AS QTDE_ORDENS
FROM CLIENTE C 
LEFT JOIN ORDEMSERVICO O
ON C.IDCLIENTE = O.IDCLIENTE
GROUP BY C.NOME;

/*QUANTIDADE DE ORDENS DE SERVIÇOS EMITIDAS NO ANO ATUAL POR EQUIPE*/
SELECT E.RESPONSAVEL AS EQUIPE,
	COUNT(O.IDORDEMSERVICO) AS QTDE_ORDENS
FROM EQUIPE E 
LEFT JOIN ORDEMSERVICO O
ON E.IDEQUIPE = O.IDEQUIPE
WHERE YEAR(DATAEMISSAO) = YEAR(current_date())
GROUP BY E.RESPONSAVEL;

/*ordens de serviços ordenadas pelo número*/
SELECT SUB.*
FROM (
SELECT O.idOrdemServico,
IOS.QUANTIDADE,
S.DESCRICAO,
S.VALOR
FROM ORDEMSERVICO O
INNER JOIN ORDEMSERVICOS_TEM_SERVICOS IOS
ON O.idOrdemServico = IOS.idOrdemServicos
LEFT JOIN SERVICOS S
ON IOS.idServicos = S.idServicos
union
SELECT O.idOrdemServico,
IP.QUANTIDADE,
P.DESCRICAO,
P.VALOR
FROM ORDEMSERVICO O
INNER JOIN ORDEMSERVICOS_TEM_PECAS IP
ON O.idOrdemServico = IP.idOrdemServicos
LEFT JOIN PECAS P
ON IP.idPecas = P.idPecas) SUB
ORDER BY SUB.idOrdemServico;


/*Valor total por ordem de serviço*/
SELECT SUB.idOrdemServico,
	SUM(SUB.VALOR) AS TotalOrdem
FROM (
SELECT O.idOrdemServico,
IOS.QUANTIDADE,
S.VALOR
FROM ORDEMSERVICO O
INNER JOIN ORDEMSERVICOS_TEM_SERVICOS IOS
ON O.idOrdemServico = IOS.idOrdemServicos
LEFT JOIN SERVICOS S
ON IOS.idServicos = S.idServicos
union
SELECT O.idOrdemServico,
IP.QUANTIDADE,
P.VALOR
FROM ORDEMSERVICO O
INNER JOIN ORDEMSERVICOS_TEM_PECAS IP
ON O.idOrdemServico = IP.idOrdemServicos
LEFT JOIN PECAS P
ON IP.idPecas = P.idPecas) SUB
group by SUB.idOrdemServico
ORDER BY SUM(SUB.VALOR) DESC;

